version: "1.0"
info:
  model: int-scaffold
packages:
- name: OriginDEV1Project
  gitServerName: remoteGit
  gitUrl: https://github.com/Hariharan-SV-IBM
  gitUsername: Hariharan-SV-IBM
  gitBranch: main
- name: WmAmazonEC2Provider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
  wpmVersion: v10.5.0
- name: PublicPrivateCheck
  gitServerName: remoteGit
  gitUrl: https://github.com/Munatri
  gitUsername: Hariharan-SV-IBM
  gitBranch: main
services:
- serviceName: project.origindev1.integrations:dafSVC
  packages:
  - name: OriginDEV1Project
    version: "1.0"
- serviceName: pub.math:randomDouble
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
